package com.example.dev.saludmock.activities;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.Toast;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.Manager;
import com.couchbase.lite.android.AndroidContext;
import com.couchbase.lite.util.Log;
import com.example.dev.saludmock.R;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by kennethrizo on 18/11/17.
 */

public class DownloadSheetToCouchbase extends AppCompatActivity{

    int idDocument;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.descargacouchbase_main);

        String nombre = getIntent().getExtras().getString("nombre");
        String mascota = getIntent().getExtras().getString("mascota");
        String telefono = getIntent().getExtras().getString("telefono");
        String direccion = getIntent().getExtras().getString("direccion");
        String edad = getIntent().getExtras().getString("edad");
        String raza = getIntent().getExtras().getString("raza");
        String tmascota = getIntent().getExtras().getString("tmascota");
        String tratamiento = getIntent().getExtras().getString("tratamiento");
        String social = getIntent().getExtras().getString("social");
        String comentario = getIntent().getExtras().getString("comentario");
        String trescatado = getIntent().getExtras().getString("trescatado");
        String fvacuna = getIntent().getExtras().getString("fvacuna");
        String fdesparacitacion = getIntent().getExtras().getString("fdesparacitacion");
        String fcelo = getIntent().getExtras().getString("fcelo");
        String tlactar = getIntent().getExtras().getString("tlactar");
        String correo = getIntent().getExtras().getString("correo");
        String dmascota = getIntent().getExtras().getString("dmascota");
        //fecha de creacion
        String numero = getIntent().getExtras().getString("numero");

        //Create a manager
        Manager manager = null;
        try{
            manager = new Manager(new AndroidContext(getApplicationContext()), Manager.DEFAULT_OPTIONS);
        }catch (IOException e){
            e.printStackTrace();
        }

        //Create or open the database named app
        Database database = null;
        try {
            database = manager.getDatabase("adla");
        }catch (CouchbaseLiteException e){
            e.printStackTrace();
        }



        //The properties that will be saved on the document
        Map<String, Object> properties = new HashMap<String, Object>();

        //properties.put("ficha", rnd.nextInt());
        //  properties.put("_rev", String.valueOf(i));

        properties.put("nombre", nombre);
        properties.put("direccion", direccion);
        properties.put("telefono", telefono);
        properties.put("correo", correo);
        properties.put("nombre_mascota", mascota);
        properties.put("tipo_mascota", tmascota);
        properties.put("raza", raza);
        properties.put("edad", edad);
        properties.put("medio", social);
        properties.put("comentarios_registro", comentario);
        properties.put("cirugia", tratamiento);
        properties.put("rescatado", trescatado);
        properties.put("vacuna", fvacuna);
        properties.put("desparacitacion", fdesparacitacion);
        properties.put("celo", fcelo);
        properties.put("lactar", tlactar);
        properties.put("created_at", numero);

        SharedPreferences preferences = getSharedPreferences("values", MODE_PRIVATE);
        idDocument = preferences.getInt("idDocument", 0);

        idDocument++;

        SharedPreferences prefs = getSharedPreferences("values", MODE_PRIVATE);
        SharedPreferences.Editor editor = prefs.edit();
        editor.putInt("idDocument", idDocument);
        editor.commit();

        String idDocumentS = Integer.toString(idDocument);

        //Create a new document
        Document document = database.getDocument(idDocumentS);
        //     UnsavedRevision revision = document.createRevision();
        //    revision.setUserProperties(properties);
        //Save the document to the database
        try {
            document.putProperties(properties);
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }

        //Log the document ID (generated by the database)
        //and properties
        Log.d("registro", String.format("Document ID :: %s", document.getId()));
        Log.d("registro", String.format("Los datos que han sido guardados son: ",
                //    (String) document.getProperty("ficha"),
                (String) document.getProperty("nombre"),
                (String) document.getProperty("direccion"),
                (String) document.getProperty("telefono"),
                (String) document.getProperty("correo"),
                (String) document.getProperty("nombre_mascota"),
                (String) document.getProperty("raza"),
                (String) document.getProperty("edad"),
                (String) document.getProperty("comentarios_registro"),
                (String) document.getProperty("cirugia"),
                (String) document.getProperty("rescatado"),
                (String) document.getProperty("vacuna"),
                (String) document.getProperty("desparacitacion"),
                (String) document.getProperty("celo"),
                (String) document.getProperty("lactar")));


        Toast.makeText(getApplicationContext(), idDocumentS, Toast.LENGTH_LONG).show();
        Intent i = new Intent(DownloadSheetToCouchbase.this, CreatePdfActivity.class);

        i.putExtra("numero_folio", idDocumentS);
        i.putExtra("nombre",nombre);
        i.putExtra("numero", numero);
        i.putExtra("mascota", mascota);
        i.putExtra("telefono", telefono);
        i.putExtra("direccion", direccion);
        i.putExtra("edad", edad);
        i.putExtra("raza", raza);
        i.putExtra("tmascota", tmascota);
        i.putExtra("tratamiento", tratamiento);
        i.putExtra("social", social);
        i.putExtra("comentario", comentario);
        i.putExtra("trescatado", trescatado);
        i.putExtra("fvacuna", fvacuna);
        i.putExtra("fdesparacitacion", fdesparacitacion);
        i.putExtra("fcelo", fcelo);
        i.putExtra("tlactar", tlactar);
        i.putExtra("correo", correo);
        i.putExtra("dmascota", dmascota);

        startActivity(i);


    }
}
